import { FoodItem } from '../types';

export const INITIAL_FOOD_ITEMS: FoodItem[] = [
  {
    id: 'food_1',
    name: 'Gryffindor Lionheart Saffron Dum Biryani',
    tagline: "Godric's Golden Saffron • 12-Hour Slow Dum Cooked",
    restaurant: 'The Great Hall Feast Kitchen',
    restaurantRating: 4.8,
    dishRating: 4.9,
    reviewCount: 3420,
    cuisine: 'North Indian / Mughlai',
    category: 'Biryani',
    price: 360,
    originalPrice: 480,
    description: "Aged Daawat basmati rice slow-cooked in sealed clay handis with succulent marinated mutton chunks, saffron milk, caramelized shallots, and secret Godric's potli spices. Served with spicy Mirchi Ka Salan and creamy Burani Raita.",
    mediaType: 'video',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/66/En.Wikipedia-VideoWiki-Biryani.webm',
    videoUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/66/En.Wikipedia-VideoWiki-Biryani.webm',
    fallbackVideoUrl: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=1080&auto=format&fit=crop',
    prepTimeMins: 22,
    distanceKm: 2.4,
    calories: 680,
    proteinGrams: 34,
    isVeg: false,
    isBestseller: true,
    isTrending: true,
    spicyLevel: 2,
    moods: ['Party', 'Late Night', 'Comfort', 'Weekend Feast'],
    cravings: ['Spicy', 'Rich', 'Meaty', 'Authentic'],
    budgetTier: 'mid',
    ingredients: ['Aged Long Grain Basmati', 'Tender Prime Cuts', 'Pure Desi Ghee', 'Saffron Strands', 'Fried Brown Onions', 'Star Anise & Shahi Jeera'],
    chefSpecialty: 'Slow dum sealed with whole wheat dough over hickory charcoal',
    likesCount: 1840,
    sharesCount: 420,
    platforms: [
      {
        platformName: 'Swiggy',
        originalPrice: 480,
        offerPrice: 288,
        promoCode: 'SWIGGYIT',
        discountText: '40% OFF up to ₹120 + Free Delivery',
        deliveryFee: 0,
        deliveryTimeMins: 28,
        rating: 4.8,
        isBestDeal: true,
        perks: ['Swiggy One Free Delivery', 'Lightning Fast Dispatch', 'Live Temperature Tag'],
        platformColor: '#FC8019',
        badge: 'Best Deal (Save ₹192)'
      },
      {
        platformName: 'Zomato',
        originalPrice: 480,
        offerPrice: 320,
        promoCode: 'ZOMATO50',
        discountText: '50% OFF up to ₹100 with Gold',
        deliveryFee: 15,
        deliveryTimeMins: 32,
        rating: 4.7,
        isBestDeal: false,
        perks: ['Zomato Gold On-Time Guarantee', 'Live Cooking Stream link'],
        platformColor: '#E23744'
      },
      {
        platformName: 'EatSure',
        originalPrice: 460,
        offerPrice: 345,
        promoCode: 'EATSURE100',
        discountText: 'Flat ₹115 OFF + Free Double Gulab Jamun',
        deliveryFee: 0,
        deliveryTimeMins: 35,
        rating: 4.5,
        isBestDeal: false,
        perks: ['Zero Artificial Flavours Guarantee', 'Double Dessert Combo'],
        platformColor: '#6B3CE8'
      },
      {
        platformName: 'Magicpin',
        originalPrice: 480,
        offerPrice: 310,
        promoCode: 'MAGIC40',
        discountText: '₹170 Cashback in Magic Points',
        deliveryFee: 25,
        deliveryTimeMins: 40,
        rating: 4.4,
        isBestDeal: false,
        perks: ['30% Dine-in Points Recharge'],
        platformColor: '#1A82E2'
      },
      {
        platformName: 'Direct',
        originalPrice: 420,
        offerPrice: 378,
        promoCode: 'DIRECT10',
        discountText: '10% Restaurant Loyalty Discount',
        deliveryFee: 30,
        deliveryTimeMins: 45,
        rating: 4.9,
        isBestDeal: false,
        perks: ['Direct from Chef Handi', 'Eco-friendly Clay Pot Packing'],
        platformColor: '#10B981'
      }
    ],
    restaurantCompetitors: [
      {
        id: 'comp_1',
        restaurantName: 'The Great Hall Feast Kitchen',
        dishVariation: 'Gryffindor Saffron Dum Biryani',
        rating: 4.8,
        reviewsCount: 3420,
        price: 288,
        distanceKm: 2.4,
        signatureStyle: 'Clay Handi Sealed with Charcoal Dum',
        whyBetter: 'Perfect rice moisture balance, no excess oil, authentic saffron fragrance.',
        hygieneScore: '98/100 (FSSAI 5-Star)',
        imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=400&auto=format&fit=crop'
      },
      {
        id: 'comp_2',
        restaurantName: 'Bawarchi Grand Shahi',
        dishVariation: 'Spicy Masaledar Andhra Dum Biryani',
        rating: 4.6,
        reviewsCount: 2190,
        price: 310,
        distanceKm: 3.8,
        signatureStyle: 'High Fire Green Chili & Black Pepper Marination',
        whyBetter: 'Extra punchy spice kick for heavy spice lovers.',
        hygieneScore: '92/100',
        imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=400&auto=format&fit=crop'
      },
      {
        id: 'comp_3',
        restaurantName: 'Behrouz Gourmet Dum',
        dishVariation: 'Zaikedaar Paneer / Mutton Biryani with Dry Fruits',
        rating: 4.4,
        reviewsCount: 1800,
        price: 360,
        distanceKm: 4.2,
        signatureStyle: 'Cashew Almond Infusion with Royal Persian Spices',
        whyBetter: 'Milder richness and luxurious presentation box with brass candle.',
        hygieneScore: '96/100',
        imageUrl: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=400&auto=format&fit=crop'
      }
    ]
  },
  {
    id: 'food_2',
    name: 'Golden Snitch Double Truffle Smash Burger',
    tagline: 'Lioncrest Angus Patty • Smoked Gouda • Truffle Aioli',
    restaurant: 'Three Broomsticks Tavern',
    restaurantRating: 4.9,
    dishRating: 4.95,
    reviewCount: 2890,
    cuisine: 'American / Gourmet Burgers',
    category: 'Burger',
    price: 280,
    originalPrice: 380,
    description: 'Double smashed crispy-edged Angus beef patties seared on cast iron, melted golden Wisconsin cheddar & aged Gouda, caramelized port onions, and house-whipped black truffle aioli in a toasted butter brioche bun.',
    mediaType: 'video',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Grilled_entrecote_20190119_2.webm',
    videoUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Grilled_entrecote_20190119_2.webm',
    fallbackVideoUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/62/CARBON_NIGHT_MARKET_%281%29.webm',
    posterUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=1080&auto=format&fit=crop',
    prepTimeMins: 15,
    distanceKm: 1.8,
    calories: 610,
    proteinGrams: 36,
    isVeg: false,
    isBestseller: true,
    isTrending: true,
    spicyLevel: 1,
    moods: ['Cheat Day', 'Late Night', 'Quick Lunch', 'Stress Buster'],
    cravings: ['Cheesy', 'Crispy', 'Juicy', 'Savory'],
    budgetTier: 'mid',
    ingredients: ['Prime Angus Beef Blend', 'Japanese Milk Brioche Bun', 'Wisconsin Aged Cheddar', 'Black Truffle Infused Aioli', 'Pickled Gherkins', 'Crispy French Butter'],
    chefSpecialty: 'Double smash technique with 450°F searing for maximum Maillard crust',
    likesCount: 2410,
    sharesCount: 680,
    platforms: [
      {
        platformName: 'Zomato',
        originalPrice: 380,
        offerPrice: 228,
        promoCode: 'TRYNEW',
        discountText: '40% OFF + Flat ₹50 Zomato Cashback',
        deliveryFee: 0,
        deliveryTimeMins: 20,
        rating: 4.9,
        isBestDeal: true,
        perks: ['Zomato Gold Priority Delivery in 20 min', 'Free Peri-Peri Dip'],
        platformColor: '#E23744',
        badge: 'Lowest Price Guaranteed (Save ₹152)'
      },
      {
        platformName: 'Swiggy',
        originalPrice: 380,
        offerPrice: 260,
        promoCode: 'PARTY50',
        discountText: '30% OFF with Swiggy Gourmet',
        deliveryFee: 20,
        deliveryTimeMins: 24,
        rating: 4.8,
        isBestDeal: false,
        perks: ['Free Seasoned Crinkle Fries on orders >₹299'],
        platformColor: '#FC8019'
      },
      {
        platformName: 'Magicpin',
        originalPrice: 380,
        offerPrice: 275,
        promoCode: 'BURGER50',
        discountText: '₹105 OFF using Magic Coins',
        deliveryFee: 25,
        deliveryTimeMins: 30,
        rating: 4.6,
        isBestDeal: false,
        perks: ['Buy 1 Get 1 Coffee voucher'],
        platformColor: '#1A82E2'
      },
      {
        platformName: 'Direct',
        originalPrice: 350,
        offerPrice: 315,
        promoCode: 'FIRSTBITE',
        discountText: '10% Direct Pickup / Delivery',
        deliveryFee: 0,
        deliveryTimeMins: 25,
        rating: 4.9,
        isBestDeal: false,
        perks: ['Custom patty doneness selection'],
        platformColor: '#10B981'
      }
    ],
    restaurantCompetitors: [
      {
        id: 'comp_burger_1',
        restaurantName: 'Three Broomsticks Tavern',
        dishVariation: 'Golden Snitch Double Truffle Smash Burger',
        rating: 4.9,
        reviewsCount: 2890,
        price: 228,
        distanceKm: 1.8,
        signatureStyle: 'High-heat smashed crispy lace edges with Truffle Glaze',
        whyBetter: 'Unmatched crust texture and pillowy soft in-house brioche.',
        hygieneScore: '99/100',
        imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=400&auto=format&fit=crop'
      },
      {
        id: 'comp_burger_2',
        restaurantName: 'Bigies Smash House',
        dishVariation: 'BBQ Smoked Bacon & Double Cheese Melt',
        rating: 4.5,
        reviewsCount: 1450,
        price: 245,
        distanceKm: 3.1,
        signatureStyle: 'Hickory Smoked Sweet BBQ reduction',
        whyBetter: 'Good for sweet-smoky sauce lovers with generous bacon strips.',
        hygieneScore: '90/100',
        imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=400&auto=format&fit=crop'
      }
    ]
  },
  {
    id: 'food_3',
    name: 'Sorting Hat Woodfired Burrata Pizza',
    tagline: 'Scarlet San Marzano • Fresh Creamy Burrata • Hand Tossed Sourdough',
    restaurant: 'Gryffindor Hearthstone Pizzeria',
    restaurantRating: 4.85,
    dishRating: 4.9,
    reviewCount: 1950,
    cuisine: 'Italian / Woodfired Pizza',
    category: 'Pizza',
    price: 340,
    originalPrice: 490,
    description: '48-hour slow fermented sourdough crust blistered at 900°F in an authentic stone oven. Topped with scarlet San Marzano tomato reduction, whole fresh creamy Burrata ball, Genovese basil pesto drizzle, toasted pine nuts, and cold-pressed EVOO.',
    mediaType: 'video',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Cooking_Squilla_mantis_with_tomato_sauce.webm',
    videoUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Cooking_Squilla_mantis_with_tomato_sauce.webm',
    fallbackVideoUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Cooking_with_Laura_Homemade_Pasta.webm',
    posterUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=1080&auto=format&fit=crop',
    prepTimeMins: 18,
    distanceKm: 2.1,
    calories: 740,
    proteinGrams: 28,
    isVeg: true,
    isBestseller: true,
    isTrending: true,
    spicyLevel: 1,
    moods: ['Weekend Feast', 'Comfort', 'Party', 'Rainy Day'],
    cravings: ['Cheesy', 'Rich', 'Crispy', 'Authentic'],
    budgetTier: 'mid',
    ingredients: ['Caputo Tipo 00 Flour', 'San Marzano DOP Tomatoes', 'Fresh Fior di Latte', 'Whole Creamy Burrata', 'Genovese Basil Pesto', 'Toasted Pine Nuts'],
    chefSpecialty: '90-second blister bake in Italian volcanic stone wood oven',
    likesCount: 3120,
    sharesCount: 890,
    platforms: [
      {
        platformName: 'Swiggy',
        originalPrice: 490,
        offerPrice: 294,
        promoCode: 'GOURMET40',
        discountText: '40% OFF on Gourmet Collection + Free Delivery',
        deliveryFee: 0,
        deliveryTimeMins: 25,
        rating: 4.9,
        isBestDeal: true,
        perks: ['Thermal Pizza Pod Delivery (Guaranteed Hot & Crispy)', 'Free Garlic Bread on orders >₹399'],
        platformColor: '#FC8019',
        badge: 'Best Deal (Save ₹196)'
      },
      {
        platformName: 'Zomato',
        originalPrice: 490,
        offerPrice: 330,
        promoCode: 'PIZZAFEST',
        discountText: 'Flat ₹160 OFF with HDFC Cards',
        deliveryFee: 20,
        deliveryTimeMins: 30,
        rating: 4.8,
        isBestDeal: false,
        perks: ['Free Chilli Infused Olive Oil Sachet'],
        platformColor: '#E23744'
      },
      {
        platformName: 'EatSure',
        originalPrice: 480,
        offerPrice: 360,
        promoCode: 'EATPIZZA',
        discountText: '25% OFF on Sourdough Special',
        deliveryFee: 0,
        deliveryTimeMins: 35,
        rating: 4.6,
        isBestDeal: false,
        perks: ['100% Preservative-free guarantee'],
        platformColor: '#6B3CE8'
      }
    ],
    restaurantCompetitors: [
      {
        id: 'comp_pizza_1',
        restaurantName: 'Gryffindor Hearthstone Pizzeria',
        dishVariation: 'Sorting Hat Burrata Pizza 11"',
        rating: 4.85,
        reviewsCount: 1950,
        price: 294,
        distanceKm: 2.1,
        signatureStyle: 'Leopard-spotted chewy sourdough crust with molten burrata core',
        whyBetter: 'Light and airy crust that doesn’t feel heavy on the stomach.',
        hygieneScore: '99/100',
        imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=400&auto=format&fit=crop'
      },
      {
        id: 'comp_pizza_2',
        restaurantName: 'Tossin Artisan Pizzeria',
        dishVariation: 'Signature Peri-Peri Four Cheese',
        rating: 4.6,
        reviewsCount: 2200,
        price: 320,
        distanceKm: 3.5,
        signatureStyle: 'Extra mozzarella cheese pull with spiced crust dust',
        whyBetter: 'Great for people who love spicy fusion flavors and loaded dips.',
        hygieneScore: '94/100',
        imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=400&auto=format&fit=crop'
      }
    ]
  },
  {
    id: 'food_4',
    name: 'Dragonfire Butter Chicken & Garlic Naan Feast',
    tagline: 'Scarlet Makhani Gravy • Clay Tandoor Roasted Chicken',
    restaurant: "Godric's Royal Feast Tandoor",
    restaurantRating: 4.75,
    dishRating: 4.8,
    reviewCount: 4100,
    cuisine: 'North Indian',
    category: 'North Indian',
    price: 270,
    originalPrice: 380,
    description: 'Boneless tender chicken tikka roasted in traditional copper tandoor, immersed in an unctuous silk scarlet tomato gravy simmered with rich butter, fresh cream, and wild kasuri methi. Paired with 2 flaky butter garlic naans and pickled onions.',
    mediaType: 'video',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Curry_Chicken.webmhd.webm',
    videoUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Curry_Chicken.webmhd.webm',
    fallbackVideoUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/66/En.Wikipedia-VideoWiki-Biryani.webm',
    posterUrl: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?q=80&w=1080&auto=format&fit=crop',
    prepTimeMins: 20,
    distanceKm: 2.7,
    calories: 720,
    proteinGrams: 42,
    isVeg: false,
    isBestseller: true,
    isTrending: false,
    spicyLevel: 2,
    moods: ['Comfort', 'Late Night', 'Weekend Feast', 'Rainy Day'],
    cravings: ['Rich', 'Creamy', 'Spicy', 'Warm & Hearty'],
    budgetTier: 'mid',
    ingredients: ['Tandoor-Charred Chicken', 'Ripe Red Tomato Puree', 'Amul White Makhan', 'Cashew Paste', 'Kashmiri Red Chili', 'Sun-Dried Kasuri Methi'],
    chefSpecialty: '18-hour slow stewed makhani sauce passed through triple fine silk mesh',
    likesCount: 2950,
    sharesCount: 510,
    platforms: [
      {
        platformName: 'EatSure',
        originalPrice: 380,
        offerPrice: 228,
        promoCode: 'DESIFEAST',
        discountText: '40% OFF Combo Meal + Free Mint Chutney & Salad',
        deliveryFee: 0,
        deliveryTimeMins: 25,
        rating: 4.8,
        isBestDeal: true,
        perks: ['Zero Extra Packaging Fee', 'Free Rasgulla Included'],
        platformColor: '#6B3CE8',
        badge: 'Best Deal (Save ₹152)'
      },
      {
        platformName: 'Swiggy',
        originalPrice: 380,
        offerPrice: 255,
        promoCode: 'SWIGGY50',
        discountText: 'Flat 30% OFF with Swiggy Money',
        deliveryFee: 15,
        deliveryTimeMins: 28,
        rating: 4.7,
        isBestDeal: false,
        perks: ['Lightning 28m delivery'],
        platformColor: '#FC8019'
      },
      {
        platformName: 'Zomato',
        originalPrice: 380,
        offerPrice: 260,
        promoCode: 'PUNJAB30',
        discountText: '30% OFF with Axis Card',
        deliveryFee: 20,
        deliveryTimeMins: 32,
        rating: 4.7,
        isBestDeal: false,
        perks: ['On-time delivery badge'],
        platformColor: '#E23744'
      }
    ],
    restaurantCompetitors: [
      {
        id: 'comp_punjab_1',
        restaurantName: "Godric's Royal Feast Tandoor",
        dishVariation: 'Dragonfire Butter Chicken Feast',
        rating: 4.75,
        reviewsCount: 4100,
        price: 228,
        distanceKm: 2.7,
        signatureStyle: 'Smoky charcoal infusion with rich cashew cream sauce',
        whyBetter: 'Silky smooth gravy texture with authentic tandoori char on the chicken.',
        hygieneScore: '98/100',
        imageUrl: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?q=80&w=400&auto=format&fit=crop'
      },
      {
        id: 'comp_punjab_2',
        restaurantName: 'Gulati Pandara Road Express',
        dishVariation: 'Classic 1952 Butter Chicken with Butter Roomali',
        rating: 4.8,
        reviewsCount: 5200,
        price: 290,
        distanceKm: 4.8,
        signatureStyle: 'Slightly sweeter tomato tang with generous desi butter slab',
        whyBetter: 'Legendary recipe unchanged for 70 years.',
        hygieneScore: '97/100',
        imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=400&auto=format&fit=crop'
      }
    ]
  },
  {
    id: 'food_5',
    name: 'Golden Galleon Steamed Butter Momos (8 Pcs)',
    tagline: 'Paper Thin Dough • Juicy Minced Filling • Fiery Red Dragon Dip',
    restaurant: 'Gryffindor Common Room Kitchen',
    restaurantRating: 4.7,
    dishRating: 4.85,
    reviewCount: 3100,
    cuisine: 'Chinese / Tibetan',
    category: 'Chinese',
    price: 140,
    originalPrice: 200,
    description: 'Delicate hand-pinched translucent golden dumplings stuffed with seasoned minced chicken, scallions, ginger, and melted butter juices. Served piping hot with signature fiery red dragon chili garlic chutney and a bowl of clear aromatic broth.',
    mediaType: 'video',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/DumplingsAnn.webm',
    videoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/DumplingsAnn.webm',
    fallbackVideoUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Chicken_potato_soup.webm',
    posterUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=1080&auto=format&fit=crop',
    prepTimeMins: 12,
    distanceKm: 1.2,
    calories: 320,
    proteinGrams: 22,
    isVeg: false,
    isBestseller: true,
    isTrending: true,
    spicyLevel: 3,
    moods: ['Late Night', 'Quick Lunch', 'Stress Buster', 'Rainy Day'],
    cravings: ['Spicy', 'Juicy', 'Steaming Hot', 'Budget Gem'],
    budgetTier: 'budget',
    ingredients: ['Fresh Hand-Kneaded Flour Skin', 'Juicy Chicken Mince', 'Spring Scallions', 'Ginger & Garlic Emulsion', 'Sichuan Peppercorns', 'Fiery Dalle Khursani Chutney'],
    chefSpecialty: 'Dumpling soup explosion inside every bite',
    likesCount: 3820,
    sharesCount: 940,
    platforms: [
      {
        platformName: 'Magicpin',
        originalPrice: 200,
        offerPrice: 110,
        promoCode: 'MOMO50',
        discountText: '45% OFF + ₹30 Magic Points',
        deliveryFee: 15,
        deliveryTimeMins: 18,
        rating: 4.8,
        isBestDeal: true,
        perks: ['Cheapest Rate on the Internet', 'Free Extra Chili Chutney Cup'],
        platformColor: '#1A82E2',
        badge: 'Super Budget Champion (Only ₹110)'
      },
      {
        platformName: 'Swiggy',
        originalPrice: 200,
        offerPrice: 135,
        promoCode: 'SNACKIT',
        discountText: '30% OFF on Snacks',
        deliveryFee: 0,
        deliveryTimeMins: 16,
        rating: 4.7,
        isBestDeal: false,
        perks: ['Swiggy Instadeliver under 18 mins'],
        platformColor: '#FC8019'
      },
      {
        platformName: 'Zomato',
        originalPrice: 200,
        offerPrice: 140,
        promoCode: 'ZOMATODEAL',
        discountText: '30% OFF with UPI Payment',
        deliveryFee: 15,
        deliveryTimeMins: 20,
        rating: 4.6,
        isBestDeal: false,
        perks: ['Gold on-time promise'],
        platformColor: '#E23744'
      }
    ],
    restaurantCompetitors: [
      {
        id: 'comp_momo_1',
        restaurantName: 'Gryffindor Common Room Kitchen',
        dishVariation: 'Golden Galleon Steamed Momos 8 Pcs',
        rating: 4.7,
        reviewsCount: 3100,
        price: 110,
        distanceKm: 1.2,
        signatureStyle: 'Translucent skin with hot broth burst inside',
        whyBetter: 'Best spice-to-juiciness ratio and super affordable pricing.',
        hygieneScore: '96/100',
        imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=400&auto=format&fit=crop'
      },
      {
        id: 'comp_momo_2',
        restaurantName: 'Wow! Momo Street Express',
        dishVariation: 'Pan Fried Schezwan Chicken Momos',
        rating: 4.2,
        reviewsCount: 4800,
        price: 165,
        distanceKm: 2.1,
        signatureStyle: 'Deep pan fried with sweet & sour schezwan toss',
        whyBetter: 'Good if you want crunchy pan-fried texture instead of steamed.',
        hygieneScore: '91/100',
        imageUrl: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?q=80&w=400&auto=format&fit=crop'
      }
    ]
  },
  {
    id: 'food_6',
    name: 'Phoenix Flame Gochujang Crispy Chicken Bowl',
    tagline: 'Double Fried Crimson Crunch • Sticky Honey Glaze • Kimchi Slaw',
    restaurant: "Fawkes' Roost Asian Grill",
    restaurantRating: 4.8,
    dishRating: 4.9,
    reviewCount: 1680,
    cuisine: 'Asian / Korean',
    category: 'Chinese',
    price: 260,
    originalPrice: 350,
    description: 'Ultracrunchy double-fried boneless chicken tenders coated in fermented Korean Gochujang chili paste, wild honey, toasted sesame, and garlic glaze. Served over steamed jasmine rice with house-fermented napa cabbage kimchi and toasted nori.',
    mediaType: 'video',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/82/Cuisine_au_wok_au_Sun_Sep_%28Beynost%29.webm',
    videoUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/82/Cuisine_au_wok_au_Sun_Sep_%28Beynost%29.webm',
    fallbackVideoUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Double-cooked_pork%2C_Xinjiang_cuisine%2C_Silk_Road_restaurant%2C_London.webm',
    posterUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=1080&auto=format&fit=crop',
    prepTimeMins: 16,
    distanceKm: 2.9,
    calories: 590,
    proteinGrams: 38,
    isVeg: false,
    isBestseller: true,
    isTrending: true,
    spicyLevel: 2,
    moods: ['Cheat Day', 'Late Night', 'Party', 'Quick Lunch'],
    cravings: ['Crispy', 'Spicy', 'Sweet & Savory', 'Crunchy'],
    budgetTier: 'mid',
    ingredients: ['Double-Fried Chicken Thighs', 'Aged Red Gochujang Paste', 'Wild Honey Glaze', 'White Sesame & Scallions', 'Sticky Jasmine Rice', 'Fermented Napa Kimchi'],
    chefSpecialty: 'Korean potato starch coating double fried for 4-hour crunch retention',
    likesCount: 2280,
    sharesCount: 610,
    platforms: [
      {
        platformName: 'Swiggy',
        originalPrice: 350,
        offerPrice: 210,
        promoCode: 'ASIANFEAST',
        discountText: '40% OFF up to ₹140 + Free Delivery',
        deliveryFee: 0,
        deliveryTimeMins: 22,
        rating: 4.8,
        isBestDeal: true,
        perks: ['Swiggy Gourmet Fast Tracker', 'Free Chopsticks & Extra Kimchi Dip'],
        platformColor: '#FC8019',
        badge: 'Best Deal (Save ₹140)'
      },
      {
        platformName: 'Zomato',
        originalPrice: 350,
        offerPrice: 245,
        promoCode: 'KPOP30',
        discountText: '30% OFF with Gold Discount',
        deliveryFee: 15,
        deliveryTimeMins: 26,
        rating: 4.7,
        isBestDeal: false,
        perks: ['Zomato Gold 10% instant rebate'],
        platformColor: '#E23744'
      }
    ],
    restaurantCompetitors: [
      {
        id: 'comp_korean_1',
        restaurantName: "Fawkes' Roost Asian Grill",
        dishVariation: 'Phoenix Flame Gochujang Rice Bowl',
        rating: 4.8,
        reviewsCount: 1680,
        price: 210,
        distanceKm: 2.9,
        signatureStyle: 'Super crunchy potato starch double-fry with authentic Korean chili paste',
        whyBetter: 'Stays crispy even 30 mins after delivery; phenomenal sweet-spicy balance.',
        hygieneScore: '97/100',
        imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=400&auto=format&fit=crop'
      }
    ]
  },
  {
    id: 'food_7',
    name: 'Lioncrest Ghee Podi Gold Masala Dosa',
    tagline: 'Golden Roast Crepe • Spiced Potato Masala • Trio Chutneys',
    restaurant: 'Hogsmeade South Kitchen',
    restaurantRating: 4.9,
    dishRating: 4.95,
    reviewCount: 6200,
    cuisine: 'South Indian',
    category: 'South Indian',
    price: 110,
    originalPrice: 150,
    description: 'Crisp golden crepe made from fermented batter, roasted in generous pure golden desi ghee, dusted with fiery Gunpowder Podi spice, and filled with mild turmeric tempered potato mash. Served with piping hot sambar and fresh coconut, tomato & mint chutneys.',
    mediaType: 'video',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/A_Aesthetic_Parota_making_part_1.ogv',
    videoUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/A_Aesthetic_Parota_making_part_1.ogv',
    fallbackVideoUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/66/En.Wikipedia-VideoWiki-Biryani.webm',
    posterUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?q=80&w=1080&auto=format&fit=crop',
    prepTimeMins: 10,
    distanceKm: 1.5,
    calories: 380,
    proteinGrams: 12,
    isVeg: true,
    isBestseller: true,
    isTrending: true,
    spicyLevel: 2,
    moods: ['Fast & Busy', 'Comfort', 'Quick Lunch', 'Weekend Feast'],
    cravings: ['Crispy', 'Spicy', 'Comfort', 'Budget Gem'],
    budgetTier: 'budget',
    ingredients: ['Fermented Rice & Urad Batter', 'Pure Desi Ghee', 'Special Gunpowder Podi', 'Hing & Mustard Spiced Potatoes', 'Fresh Coconut Chutney', 'Tamarind Drumstick Sambar'],
    chefSpecialty: 'Continuous clarified ghee basting on heavy cast-iron tawa',
    likesCount: 4900,
    sharesCount: 1250,
    platforms: [
      {
        platformName: 'Zomato',
        originalPrice: 150,
        offerPrice: 85,
        promoCode: 'SOUTHFOOD',
        discountText: 'Flat 40% OFF with Instant UPI',
        deliveryFee: 10,
        deliveryTimeMins: 15,
        rating: 4.9,
        isBestDeal: true,
        perks: ['Zomato 15-min Superfast Delivery', 'Double Podi Pack free'],
        platformColor: '#E23744',
        badge: 'Absolute Best Deal (Only ₹85)'
      },
      {
        platformName: 'Swiggy',
        originalPrice: 150,
        offerPrice: 99,
        promoCode: 'BREAKFAST',
        discountText: '33% OFF on Morning & All-day Classics',
        deliveryFee: 15,
        deliveryTimeMins: 18,
        rating: 4.9,
        isBestDeal: false,
        perks: ['Free Filter Coffee Coupon on next order'],
        platformColor: '#FC8019'
      },
      {
        platformName: 'Direct',
        originalPrice: 120,
        offerPrice: 110,
        promoCode: 'DIRECTTAKE',
        discountText: 'Takeaway standard rate',
        deliveryFee: 20,
        deliveryTimeMins: 20,
        rating: 4.9,
        isBestDeal: false,
        perks: ['Banana leaf packaging'],
        platformColor: '#10B981'
      }
    ],
    restaurantCompetitors: [
      {
        id: 'comp_dosa_1',
        restaurantName: 'Hogsmeade South Kitchen',
        dishVariation: 'Lioncrest Ghee Podi Masala Dosa',
        rating: 4.9,
        reviewsCount: 6200,
        price: 85,
        distanceKm: 1.5,
        signatureStyle: 'High ghee golden crust with aromatic gunpowder podi',
        whyBetter: 'Iconic golden taste with highest quality ghee and vibrant chutneys.',
        hygieneScore: '99/100',
        imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?q=80&w=400&auto=format&fit=crop'
      },
      {
        id: 'comp_dosa_2',
        restaurantName: 'Vidyarthi Bhavan Legacy',
        dishVariation: 'Thick Fluffy Benne Dosa with Potato Sagu',
        rating: 4.7,
        reviewsCount: 7800,
        price: 95,
        distanceKm: 4.2,
        signatureStyle: 'Thick spongy crispy exterior with butter pools',
        whyBetter: 'Historic nostalgia recipe with slightly softer middle sponge.',
        hygieneScore: '92/100',
        imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=400&auto=format&fit=crop'
      }
    ]
  },
  {
    id: 'food_8',
    name: 'Cauldron Molten Dark Chocolate Lava Cake',
    tagline: '70% Valrhona Cocoa • Molten Ganache Core • Madagascar Vanilla Gelato',
    restaurant: 'Honeydukes Artisan Patisserie',
    restaurantRating: 4.8,
    dishRating: 4.9,
    reviewCount: 2450,
    cuisine: 'Dessert / Bakery',
    category: 'Dessert',
    price: 180,
    originalPrice: 250,
    description: 'Decadent individual dark chocolate cauldron baked with 70% pure Belgian cocoa. When cut open, a luscious river of warm bittersweet chocolate ganache cascades over your spoon. Served with a scoop of Madagascar vanilla bean gelato.',
    mediaType: 'video',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Chocolate_cake.ogv',
    videoUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Chocolate_cake.ogv',
    fallbackVideoUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Drinking_Chocolate.webm',
    posterUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=1080&auto=format&fit=crop',
    prepTimeMins: 10,
    distanceKm: 1.9,
    calories: 450,
    proteinGrams: 8,
    isVeg: true,
    isBestseller: true,
    isTrending: true,
    spicyLevel: 1,
    moods: ['Stress Buster', 'Late Night', 'Cheat Day', 'Weekend Feast'],
    cravings: ['Sweet', 'Rich', 'Warm & Gooey', 'Chocolate Paradise'],
    budgetTier: 'budget',
    ingredients: ['70% Belgian Dark Chocolate', 'French Butter', 'Free Range Eggs/Flax Egg', 'Madagascar Vanilla Pod', 'Sea Salt Flakes', 'Pure Cocoa Powder'],
    chefSpecialty: 'Precise 7-minute bake to achieve flawless molten chocolate river center',
    likesCount: 3410,
    sharesCount: 780,
    platforms: [
      {
        platformName: 'Swiggy',
        originalPrice: 250,
        offerPrice: 125,
        promoCode: 'SWEETCRAVE',
        discountText: '50% OFF up to ₹125 on Desserts',
        deliveryFee: 0,
        deliveryTimeMins: 18,
        rating: 4.8,
        isBestDeal: true,
        perks: ['Insulated Foil Warmer Pack', 'Free Dessert Spoon & Napkin'],
        platformColor: '#FC8019',
        badge: 'Best Sweet Deal (Save ₹125)'
      },
      {
        platformName: 'Zomato',
        originalPrice: 250,
        offerPrice: 155,
        promoCode: 'DESSERT30',
        discountText: '30% OFF + 10% Gold discount',
        deliveryFee: 15,
        deliveryTimeMins: 22,
        rating: 4.7,
        isBestDeal: false,
        perks: ['Zomato Sweet Tooth Badge'],
        platformColor: '#E23744'
      },
      {
        platformName: 'EatSure',
        originalPrice: 240,
        offerPrice: 168,
        promoCode: 'EATSWEET',
        discountText: '30% OFF on Bakes',
        deliveryFee: 0,
        deliveryTimeMins: 25,
        rating: 4.6,
        isBestDeal: false,
        perks: ['No palm oil certified'],
        platformColor: '#6B3CE8'
      }
    ],
    restaurantCompetitors: [
      {
        id: 'comp_dessert_1',
        restaurantName: 'Honeydukes Artisan Patisserie',
        dishVariation: 'Cauldron Molten Lava Cake with Gelato',
        rating: 4.8,
        reviewsCount: 2450,
        price: 125,
        distanceKm: 1.9,
        signatureStyle: 'High-cocoa Belgian chocolate with silky molten center',
        whyBetter: 'Not overly sugary, intense deep cocoa aroma with genuine vanilla bean.',
        hygieneScore: '98/100',
        imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=400&auto=format&fit=crop'
      }
    ]
  },
  {
    id: 'food_9',
    name: 'Quidditch Captain High-Protein Power Bowl',
    tagline: 'Flame-Charred Chicken • Hass Avocado Guac • Cilantro Lime Rice',
    restaurant: 'Gryffindor Athletics Fresh Bar',
    restaurantRating: 4.75,
    dishRating: 4.8,
    reviewCount: 1540,
    cuisine: 'Mexican / Healthy Bowls',
    category: 'Mexican',
    price: 250,
    originalPrice: 340,
    description: 'High-protein power bowl packed with grilled citrus-marinated chicken breast, warm cilantro lime brown rice, slow-simmered black beans, fire-roasted sweet corn salsa, charred bell peppers, fresh hand-mashed Hass avocado guacamole, and smoky chipotle crema.',
    mediaType: 'video',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Home-style_aubergine%2C_Xinjiang_cuisine%2C_Silk_Road_restaurant%2C_London.webm',
    videoUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Home-style_aubergine%2C_Xinjiang_cuisine%2C_Silk_Road_restaurant%2C_London.webm',
    fallbackVideoUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/82/Cuisine_au_wok_au_Sun_Sep_%28Beynost%29.webm',
    posterUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?q=80&w=1080&auto=format&fit=crop',
    prepTimeMins: 14,
    distanceKm: 2.3,
    calories: 490,
    proteinGrams: 44,
    isVeg: false,
    isBestseller: false,
    isTrending: true,
    spicyLevel: 1,
    moods: ['Fitness Fuel', 'Fast & Busy', 'Quick Lunch', 'Healthy Clean'],
    cravings: ['Fresh & Light', 'Protein Power', 'Tangy & Zesty'],
    budgetTier: 'mid',
    ingredients: ['Charred Herb Chicken Breast', 'Fresh Hass Guacamole', 'Cilantro Lime Rice', 'Black Beans & Roasted Sweetcorn', 'Pico de Gallo', 'House Chipotle Crema'],
    chefSpecialty: 'Made fresh to order with zero refined sugar and cold-pressed olive oil dressing',
    likesCount: 1980,
    sharesCount: 380,
    platforms: [
      {
        platformName: 'Swiggy',
        originalPrice: 340,
        offerPrice: 199,
        promoCode: 'HEALTHY40',
        discountText: '40% OFF on Fit & Healthy collection',
        deliveryFee: 0,
        deliveryTimeMins: 20,
        rating: 4.8,
        isBestDeal: true,
        perks: ['Accurate Calorie & Macro Count Guaranteed', 'Free Kombucha Voucher'],
        platformColor: '#FC8019',
        badge: 'Best Deal (Save ₹141)'
      },
      {
        platformName: 'Zomato',
        originalPrice: 340,
        offerPrice: 238,
        promoCode: 'FITNESS30',
        discountText: '30% OFF with Gold',
        deliveryFee: 15,
        deliveryTimeMins: 24,
        rating: 4.7,
        isBestDeal: false,
        perks: ['Gold on-time guarantee'],
        platformColor: '#E23744'
      }
    ],
    restaurantCompetitors: [
      {
        id: 'comp_mex_1',
        restaurantName: 'Gryffindor Athletics Fresh Bar',
        dishVariation: 'Quidditch High Protein Avocado Fiesta Bowl',
        rating: 4.75,
        reviewsCount: 1540,
        price: 199,
        distanceKm: 2.3,
        signatureStyle: 'Fresh California style with generous fresh guacamole scoop',
        whyBetter: '44g pure protein per bowl with clean ingredients and no heavy sodium.',
        hygieneScore: '99/100',
        imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?q=80&w=400&auto=format&fit=crop'
      }
    ]
  },
  {
    id: 'food_10',
    name: "Godric's Hollow Jumbo Cheese Vada Pav & Chai",
    tagline: 'Spiced Golden Batata Vada • Melted Butter Cheese • Red Garlic Dust',
    restaurant: 'Hogsmeade Street Bazaar',
    restaurantRating: 4.65,
    dishRating: 4.8,
    reviewCount: 4890,
    cuisine: 'Street Food',
    category: 'Street Food',
    price: 90,
    originalPrice: 140,
    description: 'Crispy batter-fried spiced potato dumpling tucked inside a soft pav bun slathered with fiery dry red garlic peanut chutney, tangy tamarind glaze, green mint coriander chutney, and a thick layer of melted cheese. Comes with 2 cups of hot, cardamom and fresh ginger brewed chai.',
    mediaType: 'video',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/62/CARBON_NIGHT_MARKET_%281%29.webm',
    videoUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/62/CARBON_NIGHT_MARKET_%281%29.webm',
    fallbackVideoUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/A_Aesthetic_Parota_making_part_1.ogv',
    posterUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=1080&auto=format&fit=crop',
    prepTimeMins: 8,
    distanceKm: 0.9,
    calories: 420,
    proteinGrams: 10,
    isVeg: true,
    isBestseller: true,
    isTrending: true,
    spicyLevel: 3,
    moods: ['Rainy Day', 'Late Night', 'Quick Lunch', 'Stress Buster'],
    cravings: ['Spicy', 'Crispy', 'Cheesy', 'Street Food Magic'],
    budgetTier: 'budget',
    ingredients: ['Mustard Spiced Mashed Potato', 'Crisp Chickpea Batter', 'Fresh Bakery Ladi Pav', 'Mumbai Dry Lasun Chutney', 'Amul Butter & Processed Cheese', 'Fresh Ginger Assam Tea'],
    chefSpecialty: 'Authentic Dadar station style dry garlic chutney recipe',
    likesCount: 4120,
    sharesCount: 1100,
    platforms: [
      {
        platformName: 'Magicpin',
        originalPrice: 140,
        offerPrice: 65,
        promoCode: 'STREET50',
        discountText: '50% OFF Street Food Craze',
        deliveryFee: 10,
        deliveryTimeMins: 14,
        rating: 4.7,
        isBestDeal: true,
        perks: ['Unbeatable ₹65 combo price', 'Free Extra Fried Salted Green Chilies'],
        platformColor: '#1A82E2',
        badge: 'Craziest Budget Deal (Only ₹65)'
      },
      {
        platformName: 'Swiggy',
        originalPrice: 140,
        offerPrice: 79,
        promoCode: 'CHAIANDSNACKS',
        discountText: '40% OFF with Swiggy Lightning',
        deliveryFee: 0,
        deliveryTimeMins: 12,
        rating: 4.8,
        isBestDeal: false,
        perks: ['Delivered hot within 15 minutes'],
        platformColor: '#FC8019'
      },
      {
        platformName: 'Zomato',
        originalPrice: 140,
        offerPrice: 85,
        promoCode: 'ZOMATOSTREET',
        discountText: '35% OFF on Street Food',
        deliveryFee: 15,
        deliveryTimeMins: 16,
        rating: 4.6,
        isBestDeal: false,
        perks: ['Zomato on-time promise'],
        platformColor: '#E23744'
      }
    ],
    restaurantCompetitors: [
      {
        id: 'comp_vada_1',
        restaurantName: 'Hogsmeade Street Bazaar',
        dishVariation: 'Jumbo Cheese Vada Pav Combo',
        rating: 4.65,
        reviewsCount: 4890,
        price: 65,
        distanceKm: 0.9,
        signatureStyle: 'Super punchy dry garlic peanut chutney and hot freshly fried vadas',
        whyBetter: 'Classic authentic street flavor at an unbeatable price.',
        hygieneScore: '94/100',
        imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=400&auto=format&fit=crop'
      }
    ]
  },
  {
    id: 'food_11',
    name: 'Sword of Gryffindor Sizzling Paneer Angara',
    tagline: 'Smoked Charcoal Infused • Malai Cottage Cheese • Mint Podi Glaze',
    restaurant: 'Leaky Cauldron Tandoor Heritage',
    restaurantRating: 4.85,
    dishRating: 4.9,
    reviewCount: 3180,
    cuisine: 'North Indian',
    category: 'North Indian',
    price: 260,
    originalPrice: 350,
    description: 'Fresh farm malai cottage cheese cubes marinated in hung curd, hand-pounded mustard oil, yellow chili, and carom seeds. Roasted over flaming charcoal skewers and served sizzling on a cast iron platter with tandoori grilled bell peppers and mint dip.',
    mediaType: 'video',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Konya_Ta%C5%9F_F%C4%B1r%C4%B1n_Kebab%C4%B1_Tarifi_Do%C4%9Fada_Kuzu_Tand%C4%B1r_Konya_FURUN_Kebab%C4%B1_Lamb_Tandoori_in_Nature-%281080p%29.webm',
    videoUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Konya_Ta%C5%9F_F%C4%B1r%C4%B1n_Kebab%C4%B1_Tarifi_Do%C4%9Fada_Kuzu_Tand%C4%B1r_Konya_FURUN_Kebab%C4%B1_Lamb_Tandoori_in_Nature-%281080p%29.webm',
    fallbackVideoUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Grilled_entrecote_20190119_2.webm',
    posterUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=1080&auto=format&fit=crop',
    prepTimeMins: 15,
    distanceKm: 2.0,
    calories: 460,
    proteinGrams: 28,
    isVeg: true,
    isBestseller: true,
    isTrending: true,
    spicyLevel: 2,
    moods: ['Party', 'Comfort', 'Weekend Feast', 'Fitness Fuel'],
    cravings: ['Spicy', 'Rich', 'Smoky Char', 'Cheesy'],
    budgetTier: 'mid',
    ingredients: ['Fresh Malai Paneer', 'Hung Greek Yoghurt', 'Kachchi Ghani Mustard Oil', 'Ajwain & Kasuri Methi', 'Tri-Color Bell Peppers', 'Smoked Dhungar Ghee'],
    chefSpecialty: 'Live charcoal Dhungar smoke infusion for restaurant-grade sizzle aroma',
    likesCount: 2750,
    sharesCount: 540,
    platforms: [
      {
        platformName: 'Swiggy',
        originalPrice: 350,
        offerPrice: 210,
        promoCode: 'SIZZLE40',
        discountText: '40% OFF + Free Tandoori Roti',
        deliveryFee: 0,
        deliveryTimeMins: 20,
        rating: 4.8,
        isBestDeal: true,
        perks: ['Swiggy Gourmet Fast Delivery', 'Insulated Sizzler Pack'],
        platformColor: '#FC8019',
        badge: 'Best Deal (Save ₹140)'
      },
      {
        platformName: 'Zomato',
        originalPrice: 350,
        offerPrice: 245,
        promoCode: 'TIKKA30',
        discountText: '30% OFF with Gold',
        deliveryFee: 15,
        deliveryTimeMins: 24,
        rating: 4.7,
        isBestDeal: false,
        perks: ['Live Kitchen View'],
        platformColor: '#E23744'
      }
    ],
    restaurantCompetitors: [
      {
        id: 'comp_paneer_1',
        restaurantName: 'Leaky Cauldron Tandoor Heritage',
        dishVariation: 'Sword of Gryffindor Paneer Angara',
        rating: 4.85,
        reviewsCount: 3180,
        price: 210,
        distanceKm: 2.0,
        signatureStyle: 'High-heat tandoor sear with meltingly soft cottage cheese core',
        whyBetter: 'Zero rubbery texture, melts instantly in mouth with pure smoky aroma.',
        hygieneScore: '99/100',
        imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=400&auto=format&fit=crop'
      }
    ]
  },
  {
    id: 'food_12',
    name: 'Three Broomsticks Shoyu Ramen with Golden Egg',
    tagline: '14-Hour Simmered Broth • Hand-Pulled Wheat Noodles • Ajitsuke Tamago',
    restaurant: 'Diagon Alley Noodle Tavern',
    restaurantRating: 4.9,
    dishRating: 4.95,
    reviewCount: 2240,
    cuisine: 'Asian / Japanese',
    category: 'Asian',
    price: 320,
    originalPrice: 420,
    description: 'Silky 14-hour simmered broth flavored with barrel-aged Japanese shoyu, springy fresh hand-pulled wavy ramen noodles, tender slow-braised chashu, jammy marinated soft-boiled egg, menma bamboo shoots, scallions, and toasted nori.',
    mediaType: 'video',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Chicken_potato_soup.webm',
    videoUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Chicken_potato_soup.webm',
    fallbackVideoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/DumplingsAnn.webm',
    posterUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=1080&auto=format&fit=crop',
    prepTimeMins: 18,
    distanceKm: 2.6,
    calories: 580,
    proteinGrams: 36,
    isVeg: false,
    isBestseller: true,
    isTrending: true,
    spicyLevel: 1,
    moods: ['Comfort', 'Late Night', 'Rainy Day', 'Weekend Feast'],
    cravings: ['Soupy', 'Warm & Hearty', 'Rich', 'Authentic'],
    budgetTier: 'mid',
    ingredients: ['Hand-Pulled Alkaline Noodles', '14h Dashi & Shoyu Broth', 'Tender Braised Chashu', 'Marinated Jammy Egg', 'Menma Bamboo Shoots', 'Toasted Sesame Chili Oil'],
    chefSpecialty: 'Broth and noodles packed in dual-compartment insulated bowls to stay springy',
    likesCount: 3560,
    sharesCount: 920,
    platforms: [
      {
        platformName: 'Zomato',
        originalPrice: 420,
        offerPrice: 252,
        promoCode: 'RAMEN40',
        discountText: '40% OFF + Free Gyoza Starter',
        deliveryFee: 0,
        deliveryTimeMins: 22,
        rating: 4.9,
        isBestDeal: true,
        perks: ['Zomato Gold Priority Delivery', 'Free Extra Ajitsuke Egg Voucher'],
        platformColor: '#E23744',
        badge: 'Best Deal (Save ₹168)'
      },
      {
        platformName: 'Swiggy',
        originalPrice: 420,
        offerPrice: 294,
        promoCode: 'JAPAN30',
        discountText: '30% OFF on Asian Cuisine',
        deliveryFee: 15,
        deliveryTimeMins: 26,
        rating: 4.8,
        isBestDeal: false,
        perks: ['Eco-friendly dual-bowl delivery'],
        platformColor: '#FC8019'
      }
    ],
    restaurantCompetitors: [
      {
        id: 'comp_ramen_1',
        restaurantName: 'Diagon Alley Noodle Tavern',
        dishVariation: 'Three Broomsticks Shoyu Chashu Ramen',
        rating: 4.9,
        reviewsCount: 2240,
        price: 252,
        distanceKm: 2.6,
        signatureStyle: 'Crystal clear rich umami broth with artisanal fresh noodles',
        whyBetter: 'Perfect noodle bounce and perfectly runny yolk soft egg.',
        hygieneScore: '99/100',
        imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=400&auto=format&fit=crop'
      }
    ]
  },
  {
    id: 'food_13',
    name: 'Firebolt Flame-Grilled Loaded Quesadilla',
    tagline: 'Melted Jack & Cheddar • Fire-Roasted Salsa • Guacamole & Sour Cream',
    restaurant: 'Gryffindor Cantina & Grill',
    restaurantRating: 4.7,
    dishRating: 4.85,
    reviewCount: 1820,
    cuisine: 'Mexican / Street Grills',
    category: 'Mexican',
    price: 230,
    originalPrice: 320,
    description: 'Crispy golden flour tortilla grilled on cast iron and folded over juicy seasoned shredded chicken breast, melted Monterey Jack and sharp Wisconsin cheddar, sweet corn, scallions, and jalapeno peppers. Served with fresh pico de gallo, sour cream, and homemade guacamole.',
    mediaType: 'video',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Double-cooked_pork%2C_Xinjiang_cuisine%2C_Silk_Road_restaurant%2C_London.webm',
    videoUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Double-cooked_pork%2C_Xinjiang_cuisine%2C_Silk_Road_restaurant%2C_London.webm',
    fallbackVideoUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Grilled_entrecote_20190119_2.webm',
    posterUrl: 'https://images.unsplash.com/photo-1618040996337-56904b7850b9?q=80&w=1080&auto=format&fit=crop',
    prepTimeMins: 14,
    distanceKm: 2.2,
    calories: 540,
    proteinGrams: 32,
    isVeg: false,
    isBestseller: false,
    isTrending: true,
    spicyLevel: 2,
    moods: ['Cheat Day', 'Late Night', 'Party', 'Quick Lunch'],
    cravings: ['Cheesy', 'Crispy', 'Spicy', 'Savory'],
    budgetTier: 'mid',
    ingredients: ['Handmade Flour Tortilla', 'Chili Lime Chicken Shreds', 'Monterey Jack & Cheddar Blend', 'Charred Corn & Jalapenos', 'Creamy Avocado Guac', 'Fresh Cilantro Pico'],
    chefSpecialty: 'Butter-toasted tortilla shell with supreme stretch cheese pull',
    likesCount: 2110,
    sharesCount: 460,
    platforms: [
      {
        platformName: 'Swiggy',
        originalPrice: 320,
        offerPrice: 176,
        promoCode: 'MEXFEST',
        discountText: '45% OFF + Free Nachos Pack',
        deliveryFee: 0,
        deliveryTimeMins: 19,
        rating: 4.8,
        isBestDeal: true,
        perks: ['Free Salsa Dip & Tortilla Chips', 'Delivered hot in foil sleeve'],
        platformColor: '#FC8019',
        badge: 'Best Deal (Save ₹144)'
      },
      {
        platformName: 'Zomato',
        originalPrice: 320,
        offerPrice: 210,
        promoCode: 'FUEGO30',
        discountText: '30% OFF with Gold Discount',
        deliveryFee: 15,
        deliveryTimeMins: 23,
        rating: 4.7,
        isBestDeal: false,
        perks: ['Fast Dispatch'],
        platformColor: '#E23744'
      }
    ],
    restaurantCompetitors: [
      {
        id: 'comp_quesa_1',
        restaurantName: 'Gryffindor Cantina & Grill',
        dishVariation: 'Firebolt Loaded Chicken Quesadilla 10"',
        rating: 4.7,
        reviewsCount: 1820,
        price: 176,
        distanceKm: 2.2,
        signatureStyle: 'High cheese stretch with crisp golden-brown griddle crust',
        whyBetter: 'Generous chicken and cheese ratio with three complimentary dips.',
        hygieneScore: '97/100',
        imageUrl: 'https://images.unsplash.com/photo-1618040996337-56904b7850b9?q=80&w=400&auto=format&fit=crop'
      }
    ]
  },
  {
    id: 'food_14',
    name: 'Golden Wand Cinnamon Sugar Churros & Dulce De Leche',
    tagline: 'Cinnamon Sugar Dusted • Valrhona Dark Chocolate • Creamy Caramel Dip',
    restaurant: "Madam Puddifoot's Sweet Treat Shop",
    restaurantRating: 4.85,
    dishRating: 4.9,
    reviewCount: 1740,
    cuisine: 'Dessert / Bakery',
    category: 'Dessert',
    price: 160,
    originalPrice: 220,
    description: 'Hot, freshly piped golden churro batons fried until golden crispy outside and tender fluffy inside. Tossed generously in fragrant cinnamon sugar and accompanied by warm Belgian dark chocolate ganache and slow-simmered dulce de leche dips.',
    mediaType: 'video',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/66/10_Irresistible_Taipei_Sweets_Under_%245_You_Must_Try%21.webm',
    videoUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/66/10_Irresistible_Taipei_Sweets_Under_%245_You_Must_Try%21.webm',
    fallbackVideoUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Cake_Pops.webmhd.webm',
    posterUrl: 'https://images.unsplash.com/photo-1624300629298-e9de39c13be5?q=80&w=1080&auto=format&fit=crop',
    prepTimeMins: 10,
    distanceKm: 1.4,
    calories: 390,
    proteinGrams: 6,
    isVeg: true,
    isBestseller: true,
    isTrending: true,
    spicyLevel: 1,
    moods: ['Cheat Day', 'Late Night', 'Stress Buster', 'Weekend Feast'],
    cravings: ['Sweet', 'Crispy', 'Warm & Gooey', 'Comfort'],
    budgetTier: 'budget',
    ingredients: ['Crisp Choux Pastry Dough', 'Saigon Cinnamon & Golden Sugar', 'Belgian Bittersweet Chocolate', 'Caramelized Dulce De Leche', 'Sea Salt Crystals'],
    chefSpecialty: 'Fried fresh strictly upon order confirmation for unbeatable crunch',
    likesCount: 2890,
    sharesCount: 670,
    platforms: [
      {
        platformName: 'Magicpin',
        originalPrice: 220,
        offerPrice: 110,
        promoCode: 'CHURRO50',
        discountText: '50% OFF Sweet Treats',
        deliveryFee: 10,
        deliveryTimeMins: 15,
        rating: 4.8,
        isBestDeal: true,
        perks: ['Flat 50% discount', 'Includes both Chocolate & Caramel dip pots'],
        platformColor: '#1A82E2',
        badge: 'Best Sweet Deal (Only ₹110)'
      },
      {
        platformName: 'Swiggy',
        originalPrice: 220,
        offerPrice: 135,
        promoCode: 'SWEETBITE',
        discountText: '38% OFF with Swiggy Instafood',
        deliveryFee: 0,
        deliveryTimeMins: 14,
        rating: 4.8,
        isBestDeal: false,
        perks: ['Insulated box to keep churros hot & crunchy'],
        platformColor: '#FC8019'
      },
      {
        platformName: 'Zomato',
        originalPrice: 220,
        offerPrice: 145,
        promoCode: 'DESSERT25',
        discountText: '25% OFF with Zomato Gold',
        deliveryFee: 15,
        deliveryTimeMins: 18,
        rating: 4.7,
        isBestDeal: false,
        perks: ['Zomato Gold on-time promise'],
        platformColor: '#E23744'
      }
    ],
    restaurantCompetitors: [
      {
        id: 'comp_churro_1',
        restaurantName: "Madam Puddifoot's Sweet Treat Shop",
        dishVariation: 'Golden Wand Cinnamon Churros 6 Pcs Duo Dip',
        rating: 4.85,
        reviewsCount: 1740,
        price: 110,
        distanceKm: 1.4,
        signatureStyle: 'Super crisp fluted ridges with piping hot airy center',
        whyBetter: 'Light and non-greasy with rich, real cocoa dipping sauce.',
        hygieneScore: '99/100',
        imageUrl: 'https://images.unsplash.com/photo-1624300629298-e9de39c13be5?q=80&w=400&auto=format&fit=crop'
      }
    ]
  }
];

export const MOOD_OPTIONS = [
  { id: 'Late Night', label: 'Late Night Craving', emoji: '🌙', desc: 'Comfort & fast delivery' },
  { id: 'Comfort', label: 'Comfort & Warm', emoji: '🛋️', desc: 'Hearty, soulful rich food' },
  { id: 'Cheat Day', label: 'Heavy Cheat Day', emoji: '🍔', desc: 'Cheese, loaded, indulgent' },
  { id: 'Fitness Fuel', label: 'Fitness & Clean', emoji: '🥗', desc: 'High protein, low carb' },
  { id: 'Stress Buster', label: 'Stress Buster', emoji: '💆', desc: 'Spicy, chocolates, crunchy' },
  { id: 'Quick Lunch', label: 'Fast & Busy (15m)', emoji: '⚡', desc: 'Quick prep & lightning dispatch' },
  { id: 'Weekend Feast', label: 'Weekend Celebration', emoji: '🎉', desc: 'Grand royal spreads' },
  { id: 'Rainy Day', label: 'Monsoon / Rainy Day', emoji: '🌧️', desc: 'Steaming hot pakoras, momos, soup' }
];

export const CRAVING_OPTIONS = [
  { id: 'Spicy', label: 'Fiery Spicy 🌶️' },
  { id: 'Cheesy', label: 'Extra Cheesy 🧀' },
  { id: 'Crispy', label: 'Deep Crispy & Crunchy 🍟' },
  { id: 'Rich', label: 'Rich & Mughlai Gravy 🍛' },
  { id: 'Sweet', label: 'Sweet & Decadent 🍫' },
  { id: 'Juicy', label: 'Juicy & Steaming 🥟' },
  { id: 'Soupy', label: 'Warm Soupy & Broth 🍜' },
  { id: 'Fresh & Light', label: 'Fresh & Clean Greens 🥑' }
];

export const BUDGET_TIERS = [
  { id: 'budget', label: 'Super Budget', priceRange: 'Under ₹150 / $2', emoji: '🏷️' },
  { id: 'mid', label: 'Value Sweet Spot', priceRange: '₹150 - ₹350 / $4', emoji: '⭐' },
  { id: 'premium', label: 'Royal Feast', priceRange: '₹350+ / $5+', emoji: '👑' }
];

export const PREP_TIME_OPTIONS = [
  { value: 12, label: 'Super Blitz (< 15 mins)' },
  { value: 20, label: 'Fast Delivery (< 20 mins)' },
  { value: 35, label: 'Anytime (< 35 mins)' }
];
